//const domain = "http://xl1916apps.mucampus.ie";
const domain = "http://localhost";
const defaultPort = "8008";
export const APIPath = domain+":"+defaultPort+"/api/";
export const WPRestPath = domain+":8000/wp-json/wp/v2/";
//export const basename = "/ui/";
export const basename = "/";
export const archivePath =  domain+"/diyhistory/archive/";
//export const basename = "/diyhistory-react/my-app/build/";
